### ISSUE TITLE
Implement TypeScript

### ISSUE THREAD

**Issue by FeTodeschini** [FeTodeschini/vegan-mundi#19]

**Comment by sandeep0009** [comment]
would like to work upon this if you want you can assign me this issue

**Comment by FeTodeschini** [comment]
Thanks for offering, Sandeep. The thing is that I am using this project as a lab for me to practice, so at this point I want to do it by myself. Maybe we can collaborate in the near future, as there is a lot of enhancements for after the MVP goes live.

**Comment by FeTodeschini** [comment]
Typescript successfully implemented. It was a lot of work to do it in an existing application.
